import { Outlet } from "react-router-dom";
import { APP_NAME } from "../config/brand";
import Navbar from "./Navbar";

export default function Layout() {
  return (
    <div className="flex min-h-screen flex-col">
      <Navbar />
      <main className="mx-auto w-full max-w-6xl flex-1 px-4 py-6 sm:px-6 sm:py-8 lg:px-8">
        <Outlet />
      </main>
      <footer className="border-t border-slate-200 bg-white px-4 py-6 text-center text-sm text-slate-500">
        {APP_NAME} — plans generated by AI. Not a substitute for medical advice.
      </footer>
    </div>
  );
}
