"""email verification share codes and plan approval

Revision ID: 38048aa1213a
Revises: f469290ef694
Create Date: 2026-09-06 17:01:55.262330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38048aa1213a'
down_revision: Union[str, None] = 'f469290ef694'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('share_code', sa.String(length=12), nullable=False))
    op.create_index(op.f('ix_customers_share_code'), 'customers', ['share_code'], unique=True)
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('disclaimer_accepted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('workout_diet_plans', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout_diet_plans', 'approved_at')
    op.drop_column('users', 'disclaimer_accepted_at')
    op.drop_column('users', 'email_verified')
    op.drop_index(op.f('ix_customers_share_code'), table_name='customers')
    op.drop_column('customers', 'share_code')
    # ### end Alembic commands ###
