"""create users coaches customers and plans

Revision ID: b60053cf1413
Revises: 
Create Date: 2026-09-06 12:13:48.725580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b60053cf1413'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('coaches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('specialization', sa.String(length=120), nullable=True),
    sa.Column('years_experience', sa.Integer(), nullable=True),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.Column('profile_completed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('coach_id', sa.UUID(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('activity_level', sa.String(length=30), nullable=True),
    sa.Column('primary_goal', sa.String(length=30), nullable=True),
    sa.Column('dietary_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('health_injury_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('profile_completed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_customers_coach_id'), 'customers', ['coach_id'], unique=False)
    op.create_table('workout_diet_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('coach_id', sa.UUID(), nullable=False),
    sa.Column('plan_type', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_diet_plans_coach_id'), 'workout_diet_plans', ['coach_id'], unique=False)
    op.create_index(op.f('ix_workout_diet_plans_customer_id'), 'workout_diet_plans', ['customer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workout_diet_plans_customer_id'), table_name='workout_diet_plans')
    op.drop_index(op.f('ix_workout_diet_plans_coach_id'), table_name='workout_diet_plans')
    op.drop_table('workout_diet_plans')
    op.drop_index(op.f('ix_customers_coach_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_table('coaches')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
