"""split names add dob and body measurements

Revision ID: bb690482a569
Revises: b60053cf1413
Create Date: 2026-09-06 14:26:49.477631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb690482a569'
down_revision: Union[str, None] = 'b60053cf1413'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('customers', sa.Column('waist_cm', sa.Float(), nullable=True))
    op.add_column('customers', sa.Column('neck_cm', sa.Float(), nullable=True))
    op.add_column('customers', sa.Column('hip_cm', sa.Float(), nullable=True))
    op.drop_column('customers', 'age')
    op.add_column('users', sa.Column('first_name', sa.String(length=60), nullable=False))
    op.add_column('users', sa.Column('last_name', sa.String(length=60), nullable=False))
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.add_column('customers', sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('customers', 'hip_cm')
    op.drop_column('customers', 'neck_cm')
    op.drop_column('customers', 'waist_cm')
    op.drop_column('customers', 'date_of_birth')
    # ### end Alembic commands ###
