"""add diet type

Revision ID: f469290ef694
Revises: bb690482a569
Create Date: 2026-09-06 14:56:46.147436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f469290ef694'
down_revision: Union[str, None] = 'bb690482a569'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('diet_type', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'diet_type')
    # ### end Alembic commands ###
